/**
 * CommentReaction automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace SdkFabric.Airtable;
public class CommentReaction
{
    [JsonPropertyName("emoji")]
    public string? Emoji { get; set; }
    [JsonPropertyName("reactingUser")]
    public CommentAuthor? ReactingUser { get; set; }
}
