/**
 * DeleteResponse automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Airtable;

public class DeleteResponse
{
    [JsonPropertyName("deleted")]
    public bool? Deleted { get; set; }

    [JsonPropertyName("id")]
    public string? Id { get; set; }

}

