/**
 * FieldOptions automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
using System.Collections.Generic;

namespace SdkFabric.Airtable;

public class FieldOptions : Dictionary<string, object>
{
}

