/**
 * FieldsTag automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */


using System.Collections.Generic;
using System.Text.Json;
using System.Threading.Tasks;
using RestSharp;
using Sdkgen.Client;
using Sdkgen.Client.Exception;

namespace SdkFabric.Airtable;

public class FieldsTag : TagAbstract {
    public FieldsTag(RestClient httpClient, Parser parser): base(httpClient, parser)
    {
    }


    public async Task<Field> Create(string baseId, string tableId, Field payload)
    {
        Dictionary<string, object> pathParams = new();
        pathParams.Add("baseId", baseId);
        pathParams.Add("tableId", tableId);

        Dictionary<string, object> queryParams = new();

        List<string> queryStructNames = new();

        RestRequest request = new(this.Parser.Url("/v0/meta/bases/:baseId/tables/:tableId/fields", pathParams), Method.Post);
        this.Parser.Query(request, queryParams, queryStructNames);
        request.AddJsonBody(JsonSerializer.Serialize(payload));

        RestResponse response = await this.HttpClient.ExecuteAsync(request);

        if (response.IsSuccessful)
        {
            return this.Parser.Parse<Field>(response.Content);
        }

        throw (int) response.StatusCode switch
        {
            400 => new ErrorException(this.Parser.Parse<Error>(response.Content)),
            403 => new ErrorException(this.Parser.Parse<Error>(response.Content)),
            404 => new ErrorException(this.Parser.Parse<Error>(response.Content)),
            500 => new ErrorException(this.Parser.Parse<Error>(response.Content)),
            _ => throw new UnknownStatusCodeException("The server returned an unknown status code"),
        };
    }

    public async Task<Field> Update(string baseId, string tableId, string columnId, Field payload)
    {
        Dictionary<string, object> pathParams = new();
        pathParams.Add("baseId", baseId);
        pathParams.Add("tableId", tableId);
        pathParams.Add("columnId", columnId);

        Dictionary<string, object> queryParams = new();

        List<string> queryStructNames = new();

        RestRequest request = new(this.Parser.Url("/v0/meta/bases/:baseId/tables/:tableId/fields/:columnId", pathParams), Method.Patch);
        this.Parser.Query(request, queryParams, queryStructNames);
        request.AddJsonBody(JsonSerializer.Serialize(payload));

        RestResponse response = await this.HttpClient.ExecuteAsync(request);

        if (response.IsSuccessful)
        {
            return this.Parser.Parse<Field>(response.Content);
        }

        throw (int) response.StatusCode switch
        {
            400 => new ErrorException(this.Parser.Parse<Error>(response.Content)),
            403 => new ErrorException(this.Parser.Parse<Error>(response.Content)),
            404 => new ErrorException(this.Parser.Parse<Error>(response.Content)),
            500 => new ErrorException(this.Parser.Parse<Error>(response.Content)),
            _ => throw new UnknownStatusCodeException("The server returned an unknown status code"),
        };
    }


}
