/**
 * RecordCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace SdkFabric.;
public class RecordCollection
{
    [JsonPropertyName("offset")]
    public string? Offset { get; set; }
    [JsonPropertyName("records")]
    public List<Record>? Records { get; set; }
}
