/**
 * User automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;
namespace SdkFabric.;
public class User
{
    [JsonPropertyName("email")]
    public string? Email { get; set; }
    [JsonPropertyName("id")]
    public string? Id { get; set; }
}
